Replace unsafe_(get|set)index with inbounds macro
This patch does two things:
* It all but completely removes `unsafe_getindex` and `unsafe_setindex!` from the standard library. This merges their method definitions into the safe flavors with a `(at)boundscheck checkbounds(...)` clause, and it replaces call-sites with `(at)inbounds A[I...]`.  A few uses remain because the inbounds macro doesn't return its value, making the construct a little awkward in some cases.
* It changes *where* bounds are checked in SubArrays. Previously, SubArrays would defer bounds checks to their parent arrays; they wouldn't check the indices directly, but rather they'd transform the indices into the proper references into the parent array, and then index into the parent array safely. E.g., previously:

    julia> A = -.5:.1:.5
           S = sub(A, 7:11)
           S[-4], S[0], S[4]
    (-0.4,0.0,0.4)

    julia> S[-6]
    ERROR: BoundsError: attempt to access -0.5:0.1:0.5
      at index [0]

This behavior is neither tested nor depended upon in the Base library, but I believe some packages have historically depended upon this.  With this patch, the behavior is much more sane; `S[0]` now immediately throws a bounds error from the SubArray itself.  I believe this is a strong requirement for making views more prominent (regardless of the syntax).